### ISSUE TITLE
After updating the drivers, it stopped working

### ISSUE THREAD

**Issue by lynther** [hashcat/hashcat#2745]
I recently updated the nvidia drivers to 465.89 and after that hashcat can't pass the "Initializing backend runtime for device #1..." benchmark also doesn't work
on version 461.92 everything works well

**Comment by Nucleoprotein** [comment]
Same here, i think it's because of OpenCL 3.0 enabled in this drivers.
```
- Num OpenCL platforms: 1
- CL_PLATFORM_NAME: NVIDIA CUDA
- CL_PLATFORM_VENDOR: NVIDIA Corporation
- CL_PLATFORM_VERSION: OpenCL 3.0 CUDA 11.3.55
- CL_PLATFORM_PROFILE: FULL_PROFILE
- Num devices: 1

  - CL_DEVICE_NAME: NVIDIA GeForce RTX 2070 SUPER
  - CL_DEVICE_VENDOR: NVIDIA Corporation
  - CL_DRIVER_VERSION: 465.89
  - CL_DEVICE_PROFILE: FULL_PROFILE
  - CL_DEVICE_VERSION: OpenCL 3.0 CUDA
  - CL_DEVICE_TYPE: GPU
  - CL_DEVICE_VENDOR_ID: 0x10DE
  - CL_DEVICE_MAX_COMPUTE_UNITS: 40
  - CL_DEVICE_MAX_CLOCK_FREQUENCY: 1815MHz
  - CL_NV_DEVICE_COMPUTE_CAPABILITY_MAJOR: 7
  - CL_NV_DEVICE_COMPUTE_CAPABILITY_MINOR: 5
  - CL_NV_DEVICE_REGISTERS_PER_BLOCK: 65536
  - CL_NV_DEVICE_WARP_SIZE: 32
  - CL_NV_DEVICE_GPU_OVERLAP: 1
  - CL_NV_DEVICE_KERNEL_EXEC_TIMEOUT: 1
  - CL_NV_DEVICE_INTEGRATED_MEMORY: 0
  - CL_DEVICE_ADDRESS_BITS: 32
  - CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2097152KB
  - CL_DEVICE_GLOBAL_MEM_SIZE: 8192MB
  - CL_DEVICE_MAX_PARAMETER_SIZE: 4352
  - CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE: 128 Bytes
  - CL_DEVICE_GLOBAL_MEM_CACHE_SIZE: 1280KB
  - CL_DEVICE_ERROR_CORRECTION_SUPPORT: NO
  - CL_DEVICE_LOCAL_MEM_TYPE: Local (scratchpad)
  - CL_DEVICE_LOCAL_MEM_SIZE: 48KB
  - CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE: 64KB
  - CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS: 3
  - CL_DEVICE_MAX_WORK_ITEM_SIZES: [1024 ; 1024 ; 64]
  - CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
  - CL_EXEC_NATIVE_KERNEL: 8757996
  - CL_DEVICE_IMAGE_SUPPORT: YES
  - CL_DEVICE_MAX_READ_IMAGE_ARGS: 256
  - CL_DEVICE_MAX_WRITE_IMAGE_ARGS: 32
  - CL_DEVICE_IMAGE2D_MAX_WIDTH: 32768
  - CL_DEVICE_IMAGE2D_MAX_HEIGHT: 32768
  - CL_DEVICE_IMAGE3D_MAX_WIDTH: 16384
  - CL_DEVICE_IMAGE3D_MAX_HEIGHT: 16384
  - CL_DEVICE_IMAGE3D_MAX_DEPTH: 16384
  - CL_DEVICE_MAX_SAMPLERS: 32
  - CL_DEVICE_PREFERRED_VECTOR_WIDTH_CHAR: 1
  - CL_DEVICE_PREFERRED_VECTOR_WIDTH_SHORT: 1
  - CL_DEVICE_PREFERRED_VECTOR_WIDTH_INT: 1
  - CL_DEVICE_PREFERRED_VECTOR_WIDTH_LONG: 1
  - CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT: 1
  - CL_DEVICE_PREFERRED_VECTOR_WIDTH_DOUBLE: 1
  - CL_DEVICE_EXTENSIONS: 19
  - Extensions:
    - cl_khr_global_int32_base_atomics
    - cl_khr_global_int32_extended_atomics
    - cl_khr_local_int32_base_atomics
    - cl_khr_local_int32_extended_atomics
    - cl_khr_fp64
    - cl_khr_3d_image_writes
    - cl_khr_byte_addressable_store
    - cl_khr_icd
    - cl_khr_gl_sharing
    - cl_nv_compiler_options
    - cl_nv_device_attribute_query
    - cl_nv_pragma_unroll
    - cl_nv_d3d10_sharing
    - cl_khr_d3d10_sharing
    - cl_nv_d3d11_sharing
    - cl_nv_copy_opts
    - cl_nv_create_buffer
    - cl_khr_int64_base_atomics
    - cl_khr_int64_extended_atomics

```
